[Feature] Page Uploader
ftlabs/ftda pull request #4
Opened 2017-09-01 14:26 UTC by Lily2point0

Electron app:
-selects folders from local machine
-identifies valid file formats and name
-checks existing files in S3
-allows single file override selection
-restricts uploads from OSB network
-displays progress and error messages

2017-09-01 16:14 UTC, seanmtracey requested changes
Questions and suggestions. Nothing hugely important.

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/folder-processor.js
> +	if (folders === undefined) return;
Can we wrap the return in `{}`.

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/folder-processor.js
> +				throw err;
If this error is throw, where is it handled?

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/folder-processor.js
> +			if(contents[0] === '.DS_Store') {
What if .DS_Store is not the first file listed in the directory?

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/folder-processor.js
> +				if((/(FTDA)-[0-9]{4}-[0-9]+(.xml)/g).test(file)) {
This should be `(FTDA)-[0-9]{4}-[0-9]{4}+(.xml)` otherwise FTDA-1945-01081234.xml counts as a valid file name

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/s3-upload.js
> +	multipartUploadThreshold: 20971520,
Why the upper limits?

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/backend/s3-upload.js
> +	const filesFound = Array.from(files).map((fileObject, i) => {
When do you use the `i` in `(fileObject, i)`?

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/index.html
> +            <input type="Submit" value="Override selected & proceed" class="o-buttons" />
`&amp;`

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/index.js
> +    mainWindow = new BrowserWindow({width: 800, height: 600, x: 560, y: -1057});
Why the large negative number? `-1057`

2017-09-01 16:14 UTC, seanmtracey commented on page-uploader/package.json
> +  "author": "Sean M. Tracey & Lily Madar",
I didn't write this code, feel free to remove me :)

2017-09-04 09:17 UTC, Lily2point0 commented on page-uploader/backend/folder-processor.js
> +			if(contents[0] === '.DS_Store') {
Then contents[0] is a valid file/folder and can be processed

2017-09-04 09:18 UTC, Lily2point0 commented on page-uploader/backend/folder-processor.js
> +				if((/(FTDA)-[0-9]{4}-[0-9]+(.xml)/g).test(file)) {
What if issues numbers become greater than 4 digits?

2017-09-04 09:18 UTC, Lily2point0 commented on page-uploader/backend/s3-upload.js
> +	multipartUploadThreshold: 20971520,
Default values I copied from the library, any suggestion for those values?

2017-09-04 09:27 UTC, Lily2point0 commented on page-uploader/index.js
> +    mainWindow = new BrowserWindow({width: 800, height: 600, x: 560, y: -1057});
Coordinates for my second screen.

2017-09-04 10:23 UTC, seanmtracey commented on page-uploader/backend/folder-processor.js
> +				if((/(FTDA)-[0-9]{4}-[0-9]+(.xml)/g).test(file)) {
It's a date stamp (0103 - Third of January / 1224 - 24 of December). It's never more than 4 numbers.

2017-09-04 10:25 UTC, seanmtracey commented on page-uploader/backend/s3-upload.js
> +	multipartUploadThreshold: 20971520,
No, just curious. If we can omit them and it still works I think we should - IIRC some of the scans of the later years are higher resolution than the older issues.

2017-09-04 10:25 UTC, seanmtracey commented on page-uploader/index.js
> +    mainWindow = new BrowserWindow({width: 800, height: 600, x: 560, y: -1057});
👍

2017-09-04 10:28 UTC, merged